sonar.projectKey=AmilcarCedano_bigroyal-aws
sonar.organization=amilcarcedano
sonar.projectName=bigroyal-aws
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.exclusions=**/node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js
