name: CI – Prod (Plan + Apply con aprobación manual)

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  TF_IN_AUTOMATION: "true"

jobs:
  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Checkov
        run: pip install checkov
      - name: Run Checkov
        run: |
          chmod +x ci/run-checkov.sh
          ci/run-checkov.sh

  terraform-plan-prod:
    name: Terraform Plan (prod)
    runs-on: ubuntu-latest
    needs: checkov
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.5"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan
        run: |
          chmod +x ci/terraform-plan.sh
          ci/terraform-plan.sh prod plan

      - name: Upload tfplan as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-prod
          path: terraform/envs/prod/tfplan

  terraform-apply-prod:
    name: Terraform Apply (prod) – Requiere aprobación
    runs-on: ubuntu-latest
    needs: terraform-plan-prod
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.5"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-prod
          path: terraform/envs/prod/

      - name: Terraform Apply
        run: ci/terraform-plan.sh prod apply
