name: CI – Prod (Plan + Apply con aprobación manual)

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  TF_IN_AUTOMATION: "true"

jobs:
  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Checkov
        run: pip install checkov
      - name: Run Checkov
        run: |
          chmod +x ci/run-checkov.sh
          ci/run-checkov.sh

  terraform-plan-prod:
    name: Terraform Plan (prod)
    runs-on: ubuntu-latest
    needs: checkov
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~> 1.5"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan
        run: |
          chmod +x ci/terraform-plan.sh
          ci/terraform-plan.sh prod plan

      - name: Upload tfplan as artifact
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: tfplan-prod
          path: terraform/envs/prod/tfplan

  terraform-apply-prod:
    name: Terraform Apply (prod) – Requiere aprobación
    runs-on: ubuntu-latest
    needs: terraform-plan-prod
    environment: prod
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "~> 1.5"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f # v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download tfplan
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: tfplan-prod
          path: terraform/envs/prod/

      - name: Terraform Apply
        run: ci/terraform-plan.sh prod apply
